"""
VINE-Agent: RAPTOR Hierarchical Knowledge Indexer
Directly ported and adapted from ReCOR-RAG (recor-rag/answer-generation.ipynb)
Extended with:
  - Agricultural-specific summarisation prompt (from prompts.py)
  - Temporal leaf node support (sensor summaries)
  - Save/load for nightly incremental rebuilds
"""

from __future__ import annotations

import asyncio
import pickle
import uuid
import logging
from collections import defaultdict, deque
from typing import Any, Dict, List, Optional, Tuple

import faiss
import numpy as np
import pandas as pd
import umap                          # umap-learn
from sklearn.mixture import GaussianMixture
from langchain_core.prompts import ChatPromptTemplate

from prompts import RAPTOR_CLUSTER_SUMMARY_PROMPT

logger = logging.getLogger(__name__)

RANDOM_SEED = 42


class Raptor:
    """
    Recursive Abstractive Processing for Tree-Organised Retrieval (RAPTOR).

    Original implementation from ReCOR-RAG codebase, adapted for the VINE
    precision-agriculture knowledge base.

    Additions vs ReCOR-RAG:
      * `VINE_summariser_prompt` — crops the summarisation prompt to be
        agronomically grounded (see prompts.py).
      * `add_temporal_nodes()` — ingests sensor time-series as NL summaries
        and includes them as leaf nodes in the tree.
    """

    # ─── Construction ────────────────────────────────────────────────────────

    def __init__(
        self,
        docs: List[str],
        summariser_model,
        embed_model,
        n_levels: int = 3,
    ):
        self.doc = docs
        self.NODE_IDS: Dict[str, str] = {}
        self.EDGES: List[Tuple[str, str]] = []
        self.summariser_model = summariser_model
        self.embed_model = embed_model
        self.n_levels = n_levels

        # Recursive build
        self.results = self.recursive_embed_cluster_summarize(
            docs, level=1, n_levels=n_levels
        )
        self.ALL_NODES = {v: {"text": k, "id": v} for k, v in self.NODE_IDS.items()}
        self.adjacency, self.roots = self.build_parent_child_adjacency()
        levels = self.compute_node_levels()
        self.levels = self.invert_levels(levels)

        # Build flat FAISS index across all levels
        self.node_embeddings_map = self._create_flat_index()
        self._build_faiss()
        logger.info(f"RAPTOR: FAISS index built with {len(self.node_embeddings_map)} nodes.")

    # ─── VINE Extension: Sensor Temporal Leaves ───────────────────────────────

    def add_temporal_nodes(self, sensor_summaries: List[str]):
        """
        Convert sensor time-series summaries (generated by data_loader.py)
        into RAPTOR leaf nodes and rebuild the FAISS index.

        Example summary:
          "Soil moisture Block A (Chardonnay) dropped from 34% to 22% VWC
           over 48 hours following the July 12 heat event (max 98°F)."
        """
        if not sensor_summaries:
            return

        logger.info(f"Adding {len(sensor_summaries)} temporal sensor leaf nodes…")
        for summary in sensor_summaries:
            if summary not in self.NODE_IDS:
                node_id = str(uuid.uuid4())
                self.NODE_IDS[summary] = node_id
                self.ALL_NODES[node_id] = {"text": summary, "id": node_id}

        # Rebuild flat embedding + FAISS
        self.node_embeddings_map = self._create_flat_index()
        self._build_faiss()
        logger.info("RAPTOR: FAISS index rebuilt with temporal sensor nodes.")

    # ─── UMAP + GMM Internals (ported from ReCOR-RAG) ───────────────────────

    def global_cluster_embeddings(
        self,
        embeddings: np.ndarray,
        dim: int,
        n_neighbors: Optional[int] = None,
        metric: str = "cosine",
    ) -> np.ndarray:
        if n_neighbors is None:
            n_neighbors = int((len(embeddings) - 1) ** 0.5)
        return umap.UMAP(
            n_neighbors=n_neighbors, n_components=dim, metric=metric
        ).fit_transform(embeddings)

    def local_cluster_embeddings(
        self, embeddings: np.ndarray, dim: int, num_neighbors: int = 10, metric: str = "cosine"
    ) -> np.ndarray:
        return umap.UMAP(
            n_neighbors=num_neighbors, n_components=dim, metric=metric
        ).fit_transform(embeddings)

    def get_optimal_clusters(
        self, embeddings: np.ndarray, max_clusters: int = 50
    ) -> int:
        max_clusters = min(max_clusters, len(embeddings))
        n_clusters = np.arange(1, max_clusters)
        bics = []
        for n in n_clusters:
            gm = GaussianMixture(n_components=n, random_state=RANDOM_SEED)
            gm.fit(embeddings)
            bics.append(gm.bic(embeddings))
        return n_clusters[np.argmin(bics)]

    def GMM_cluster(
        self, embeddings: np.ndarray, threshold: float, random_state: int = 0
    ):
        n_clusters = self.get_optimal_clusters(embeddings)
        gm = GaussianMixture(n_components=n_clusters, random_state=random_state)
        gm.fit(embeddings)
        probs = gm.predict_proba(embeddings)
        labels = [np.where(prob > threshold)[0] for prob in probs]
        return labels, n_clusters

    def perform_clustering(
        self, embeddings: np.ndarray, dim: int, threshold: float
    ) -> List[np.ndarray]:
        if len(embeddings) <= dim + 1:
            return [np.array([0]) for _ in range(len(embeddings))]
        reduced_global = self.global_cluster_embeddings(embeddings, dim)
        global_clusters, n_global = self.GMM_cluster(reduced_global, threshold)
        all_local = [np.array([]) for _ in range(len(embeddings))]
        total = 0
        for i in range(n_global):
            mask = np.array([i in gc for gc in global_clusters])
            gc_embeds = embeddings[mask]
            if len(gc_embeds) == 0:
                continue
            if len(gc_embeds) <= dim + 1:
                local_clusters = [np.array([0]) for _ in gc_embeds]
                n_local = 1
            else:
                reduced_local = self.local_cluster_embeddings(gc_embeds, dim)
                local_clusters, n_local = self.GMM_cluster(reduced_local, threshold)
            for j in range(n_local):
                lc_embeds = gc_embeds[np.array([j in lc for lc in local_clusters])]
                indices = np.where((embeddings == lc_embeds[:, None]).all(-1))[1]
                for idx in indices:
                    all_local[idx] = np.append(all_local[idx], j + total)
            total += n_local
        return all_local

    # ─── Embed + Cluster Texts ────────────────────────────────────────────────

    def embed(self, texts: List[str]) -> np.ndarray:
        vecs = self.embed_model.embed_documents(texts)
        return np.array(vecs)

    def embed_cluster_texts(self, texts: List[str]) -> pd.DataFrame:
        embeds = self.embed(texts)
        clusters = self.perform_clustering(embeds, dim=10, threshold=0.1)
        df = pd.DataFrame({"text": texts, "embd": list(embeds), "cluster": clusters})
        return df

    def fmt_txt(self, df: pd.DataFrame) -> str:
        return "--- --- \n --- --- ".join(df["text"].tolist())

    def embed_cluster_summarize_texts(
        self, texts: List[str], level: int
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        df_clusters = self.embed_cluster_texts(texts)
        expanded = []
        for _, row in df_clusters.iterrows():
            for c in row["cluster"]:
                expanded.append({"text": row["text"], "embd": row["embd"], "cluster": c})
        expanded_df = pd.DataFrame(expanded)
        all_clusters = expanded_df["cluster"].unique()
        logger.info(f"Level {level}: {len(all_clusters)} clusters found.")

        # Build prompts for each cluster — use VINE agricultural summary prompt
        prompts_list = []
        for i in all_clusters:
            cluster_df = expanded_df[expanded_df["cluster"] == i]
            formatted = self.fmt_txt(cluster_df)
            prompt_txt = RAPTOR_CLUSTER_SUMMARY_PROMPT.format(context=formatted)
            prompts_list.append(prompt_txt)

        # Batch synchronous summarisation using LangChain .batch() API.
        # ChatGroq and most LangChain LLMs support .batch(); we fall back
        # to serial .invoke() for LLMs that do not.
        from langchain_core.messages import HumanMessage as _HumanMessage
        try:
            raw_responses = self.summariser_model.batch(
                [[_HumanMessage(content=p)] for p in prompts_list]
            )
            summaries = [
                r.content if hasattr(r, "content") else str(r)
                for r in raw_responses
            ]
        except Exception as batch_err:
            logger.warning(f"LLM.batch() failed ({batch_err}); falling back to serial invoke.")
            summaries = []
            for p in prompts_list:
                resp = self.summariser_model.invoke([_HumanMessage(content=p)])
                summaries.append(resp.content if hasattr(resp, "content") else str(resp))

        df_summary = pd.DataFrame({
            "summaries": summaries,
            "level": [level] * len(summaries),
            "cluster": list(all_clusters),
        })
        return df_clusters, df_summary

    # ─── Tree Building ────────────────────────────────────────────────────────

    def get_id_for_text(self, text: str) -> str:
        if text not in self.NODE_IDS:
            self.NODE_IDS[text] = str(uuid.uuid4())
        return self.NODE_IDS[text]

    def recursive_embed_cluster_summarize(
        self, texts: List[str], level: int = 1, n_levels: int = 3
    ) -> Dict[int, Tuple[pd.DataFrame, pd.DataFrame]]:
        results: Dict = {}
        if level == 1:
            for t in texts:
                self.get_id_for_text(t)
        df_clusters, df_summary = self.embed_cluster_summarize_texts(texts, level)
        results[level] = (df_clusters, df_summary)

        for _, row in df_summary.iterrows():
            summary_text = row["summaries"]
            summary_cluster = row["cluster"]
            summary_id = self.get_id_for_text(summary_text)
            children_df = df_clusters[df_clusters["cluster"] == summary_cluster]
            for child_text in children_df["text"].tolist():
                child_id = self.get_id_for_text(child_text)
                self.EDGES.append((child_id, summary_id))

        if level < n_levels and df_summary["cluster"].nunique() > 1:
            next_results = self.recursive_embed_cluster_summarize(
                df_summary["summaries"].tolist(), level + 1, n_levels
            )
            results.update(next_results)
        return results

    def build_parent_child_adjacency(self, NODE_IDS=None, EDGES=None):
        if NODE_IDS is None:
            NODE_IDS = self.NODE_IDS
        if EDGES is None:
            EDGES = self.EDGES
        adjacency: Dict[str, List[str]] = defaultdict(list)
        all_children, all_parents = set(), set()
        for child, parent in EDGES:
            adjacency[parent].append(child)
            all_children.add(child)
            all_parents.add(parent)
        return adjacency, list(all_parents - all_children)

    def compute_node_levels(self, adjacency=None) -> Dict[str, int]:
        if adjacency is None:
            adjacency = self.adjacency
        nodes = set(adjacency.keys())
        for children in adjacency.values():
            nodes.update(children)
        leaves = [n for n in nodes if n not in adjacency]
        levels: Dict[str, int] = {leaf: 0 for leaf in leaves}
        reverse_adj: Dict[str, List[str]] = defaultdict(list)
        for parent, children in adjacency.items():
            for c in children:
                reverse_adj[c].append(parent)
        queue = deque(leaves)
        while queue:
            node = queue.popleft()
            for parent in reverse_adj[node]:
                levels[parent] = max(levels.get(parent, 0), levels[node] + 1)
                queue.append(parent)
        return levels

    def invert_levels(self, levels: dict) -> Dict[int, List[str]]:
        inv: Dict[int, List[str]] = {}
        for node, lvl in levels.items():
            inv.setdefault(lvl, []).append(node)
        return inv

    # ─── FAISS Index ──────────────────────────────────────────────────────────

    def _create_flat_index(self) -> Dict[str, np.ndarray]:
        """Flatten all levels into {node_id: embedding}."""
        node_embeddings: Dict[str, np.ndarray] = {}
        for level, (df_clusters, _) in self.results.items():
            for _, row in df_clusters.iterrows():
                text = row["text"]
                if text in self.NODE_IDS:
                    node_embeddings[self.NODE_IDS[text]] = np.array(row["embd"])
        # Fill any missing (e.g., root summaries)
        for node_id, content in self.ALL_NODES.items():
            if node_id not in node_embeddings:
                emb = self.embed_model.embed_documents([content["text"]])[0]
                node_embeddings[node_id] = np.array(emb)
        return node_embeddings

    def _build_faiss(self):
        """Build/rebuild FAISS IndexIDMap from node_embeddings_map."""
        all_embeds = np.array(
            list(self.node_embeddings_map.values()), dtype="float32"
        )
        dim = all_embeds.shape[1]
        self.node_id_to_int = {nid: i for i, nid in enumerate(self.node_embeddings_map)}
        self.int_to_node_id = {i: nid for nid, i in self.node_id_to_int.items()}
        int_ids = np.array(list(self.node_id_to_int.values()), dtype="int64")
        base_index = faiss.IndexFlatL2(dim)
        self.index = faiss.IndexIDMap(base_index)
        self.index.add_with_ids(all_embeds, int_ids)

    # ─── Retrieval ────────────────────────────────────────────────────────────

    def retrieve_collapsed(self, query: str, top_k: int = 10) -> List[Dict]:
        """Retrieve top-k nodes via collapsed-tree vector search."""
        query_vec = np.array(
            self.embed_model.embed_documents([query]), dtype="float32"
        )
        _, int_ids = self.index.search(query_vec, top_k)
        results = []
        for iid in int_ids[0]:
            if iid == -1:
                continue
            node_id = self.int_to_node_id[iid]
            results.append({"id": node_id, "text": self.ALL_NODES[node_id]["text"]})
        return results

    def get_leaf_nodes(self) -> List[str]:
        """Return all leaf node IDs (nodes with no children)."""
        parent_nodes = set(self.adjacency.keys())
        return [nid for nid in self.NODE_IDS.values() if nid not in parent_nodes]

    def filter_leaf_nodes(self, node_ids: List[str]) -> List[str]:
        return [nid for nid in node_ids if nid not in self.adjacency]

    # ─── Persistence ─────────────────────────────────────────────────────────

    def save(self, filepath: str):
        state = {k: getattr(self, k) for k in [
            "doc", "NODE_IDS", "EDGES", "results", "ALL_NODES",
            "adjacency", "roots", "levels", "n_levels"
        ]}
        with open(filepath, "wb") as f:
            pickle.dump(state, f)
        logger.info(f"RAPTOR tree saved to {filepath}")

    @classmethod
    def load(cls, filepath: str, summariser_model, embed_model) -> "Raptor":
        with open(filepath, "rb") as f:
            state = pickle.load(f)
        instance = cls.__new__(cls)
        for k, v in state.items():
            setattr(instance, k, v)
        instance.summariser_model = summariser_model
        instance.embed_model = embed_model
        instance.node_embeddings_map = instance._create_flat_index()
        instance._build_faiss()
        logger.info(f"RAPTOR tree loaded from {filepath}")
        return instance
